FROM node:alpine

WORKDIR /usr/src/app/client

COPY ["package.json", "package-lock.json", "./"]
RUN npm install --silent
RUN npm install react-scripts@3.3.1 -g --silent

COPY . .

EXPOSE 3000

CMD ["npm", "start"]